Sprint 6 solution
Smistav/java-kanban pull request #1
Opened 2024-02-22 08:19 UTC by Smistav

2024-02-23 19:06 UTC, YazykovMikhail requested changes

2024-02-23 19:06 UTC, YazykovMikhail commented on src/service/InMemoryHistoryManager.java
> +        history.put(task.getId(), newTail);
Вынеси эту строчку в метод add
Все таки linkLast отвеает за настрйку ссылок, за добаление отвечает метод add

2024-02-26 06:12 UTC, Smistav commented on src/service/InMemoryHistoryManager.java
> +        history.put(task.getId(), newTail);
исправил

2024-02-26 08:14 UTC, YazykovMikhail approved these changes

2024-02-26 08:14 UTC, YazykovMikhail commented on src/service/InMemoryHistoryManager.java
> +        history.put(task.getId(), new Node(tail, task, null));
Вместо этого:
```
history.put(task.getId(), new Node(tail, task, null));
linkLast(task);
```
Лучше вот в такой последовательности:
```
		linkLast(task);
		history.put(task.getId(), last);
```
Иначе получаетя ты создаешь новую задачу и добавляешь, а не добавляешь ту которая была создава в методе linkLast. 
А так после отработтаного метода linkLast новая нода будет находтся в tail и как раз ее мы и добавляем в историю.

2024-02-26 08:23 UTC, YazykovMikhail approved these changes

2024-02-26 08:33 UTC, Smistav commented on src/service/InMemoryHistoryManager.java
> +        history.put(task.getId(), new Node(tail, task, null));
Точно. Не доглядел. Поправил

2024-02-26 11:39 UTC, merged